services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: macbook
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://macbook:secret@db/todo_db
    depends_on:
      - db
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - api